react-native-community/releases

README.md

This PR is to revise the readme to add verbiage about the requesting of backport/cherrypicking. For now, single version-specific issues can be labelled and used. I'm curious about your thoughts on asking users to open issues for their own backport/cherrypicking requests. I don't have a strong opinion at this point as to the better strategy, however the decision does impact what the `README` should state :)

README verbiage for requesting backport/cherrypicking of changes

---

CHANGELOG.md

> Make sure `refreshControl` shows up on initial render if specified
this was already released in 0.53 as seen in the 0.53 changelog

fix a mistake in 0.54 release

---

CHANGELOG.md

Square brackets in Changelog are meant to link to the changes between the current and last version based on keepachangelog's format.

Fix format of Changelog

---

CHANGELOG.md

The previously introduced release notes had some markdownlint errors that were getting in the way of commits. I've addressed those issues and brought the 0.56 changelog more in line with the previous changelogs. Not knocking the approach taken -- just looking for consistency. Separately we should discuss the merits of changing the format.

Address markdownlint validation issues

---

CHANGELOG.md

@kelset brought to my attention that two significant changes were missing from the 0.56 changelog. I've placed them in the _changed_ section with a "BLOCKED" tag on it, but others may suggest that these should be "hoisted" to the top section.

Added two missing breaking changes to 0.56

---

CHANGELOG.md

Given that this release still breaks with a fresh `react-native init`, let's make sure to let people know the workaround.

Update Changelog to display known issues with Xcode 10

---

CHANGELOG.md

Given that people want to test Hooks so badly, it's better to be clear upfront.

Better explanation of RN support for 16.6+

---

CHANGELOG.md
changelog-generator.js

This PR brings in the 0.57.5 changelog plus a fix to the changelog generator to make it work with patch releases (as referenced via commit hashes).

0.57.5 changelog

---

CHANGELOG.md

These changes are internal only and don't effect users of React Native.
cc @turnrye

Removing internal only changes from changelog

---

CHANGELOG.md

In [this commit](https://github.com/facebook/react-native/commit/0cd3994f1a4ec1172af840cf5de3dddb1ae9e9c4), the way modules are accessed internally was changed. As such, whenever any userland code tries to access the instance of a Native Module, the app crashes. This is because all such native modules now require a `@ReactModule` annotation at the top which is the public name of the native module.
This was also reported in another repo: https://github.com/oney/react-native-webrtc/issues/575 and fixed like so: https://github.com/oney/react-native-webrtc/commit/8def7d0dc9370934a4d56770d63d742c2a203fea

Add missing breaking change for 0.58

---

CHANGELOG.md

Changelog for the latest 0.58.5 version.

Chore: 0.58.5 changelog

---

CHANGELOG.md

Fix the link for `release candidate phase` becomes un-linkable on GitHub. Pointing to `issues/79` instead of `issues/41`.

Fix malformed markdown

---

CHANGELOG.md

Having `removeClippedSubviews` default to `true` on Android affects `FlatList`s that use offscreen content, for example to animate it in on a swipe. This makes this change significant enough to end up in the changelog.

Add `removeClippedSubviews` Android change

---

README.md

It looks like the repo was renamed. For the most part the redirects work, however, the badges were broken. This PR fixes them 👍

Fix the repo links in the README

---

CHANGELOG.md

This adds in two missing 0.60 changelog entries that are related to fetch
[h5e36b0c](https://github.com/facebook/react-native/commit/5e36b0c) and [5447196](https://github.com/facebook/react-native/commit/5447196) (by @janicduplessis)

Add two missing 0.60 fetch-related changelog entries

---

changelog-generator.js

Facebook employees have been tagging their commits with [Internal] in order to remove them from the changelog. This wasn't being picked up by the changelog generator. This is an example commit that wasn't being filtered: https://github.com/facebook/react-native/commit/40ee0ad
The commit summary is:
```
LogBox - Re-apply badge color fix
Summary:
The previous diff mistakenly landed an old version
Changelog: [Internal]
```
The script was only looking for [Internal] in `LogBox - Re-apply badge color fix`. Now it looks for it on any line. 
Before this change:
```
$ yarn generate -b 8c7ec519812c570535912c45dd81db51ba2fdd31 -c bdd1a675ba6949868d11ef0c3dccaa8f336ca384 | wc -l
284
```
After:
```
$ yarn generate -b 8c7ec519812c570535912c45dd81db51ba2fdd31 -c bdd1a675ba6949868d11ef0c3dccaa8f336ca384 …
```

Filter out internal commits from the changelog

---

changelog-generator.js

*This PR is based on https://github.com/react-native-community/releases/pull/152 and thus includes those changes as well. Once that is merged this will get simplified*
This command now includes a breaking changes section
```
$ yarn generate -b 8c7ec519812c570535912c45dd81db51ba2fdd31 -c bdd1a675ba6949868d11ef0c3dccaa8f336ca384
- Animated: Remove `defaultProps` Parameter ([a70987c](https://github.com/facebook/react-native/commit/a70987c) by [@yungsters](https://github.com/yungsters))
- Remove TextInput's `inputView` prop ([1804e7c](https://github.com/facebook/react-native/commit/1804e7c) by [@TheSavior](https://github.com/TheSavior))
- Changelog: [General] [Changed] Split NativeImageLoader into NativeImageLoaderAndroid and NativeImageLoaderIOS …
```

Add a breaking changes section to the changelog

---

.github/ISSUE_TEMPLATE.md
CHANGELOG.md

This PR update react native docs links to new domain: reactnative.dev
Open links in changed files

docs: update documentation links to reactnative.dev

---

CHANGELOG.md

This MR just moves around some changelog items that I think were in the wrong section. Let me know if any of the moves don't seem right!
A couple notes:
- There's still a lot of noise in some of the sections, pending FB doing their changelog sweep.
- I tried not to touch the same commits that @rickhanlonii and the FB crew might touch. That means that I didn't mark anything as to-remove, or touch any unknowns that had a known committer, since FB might want to move those.
- The CLI version bump being in "breaking" specifically comes from a single incident where changes to the CLI (that didn't make it into the changelog) broke one of my team's build scripts. (This was when the CLI wasn't in its own repo.)
I'll probably take another look after FB makes their changes, depending on the scope of …

changelog: move around some misplaced commits

---

CHANGELOG.md

There were apparently some merging issues that resulted in duplicate changelog entries; this PR removes the duplicates. It also makes a couple minor consistency changes to changelog item descriptions.
Note that this definitely isn't release-blocking! I can change this to point at master if the changelog gets merged before this.

changelog: removed duplicates and fixed inconsistent formatting

---

CHANGELOG.md

This PR updates the 0.62 changelog description to be in line with the [blog post](https://github.com/facebook/react-native-website/pull/1778).
I also remove a few more commits that are internal only.

Update 0.62 description

---

CHANGELOG.md

As noted in https://github.com/facebook/react-native/issues/28270
Related to https://github.com/react-native-community/upgrade-support/issues/19
The upgrade to Hermes 0.4.0 itself isn’t really breaking, but I thought that this was perhaps the most intuitive way for users to find their issue.

[CHANGELOG/v0.62.0] Note required ProGuard rule

---

.github/ISSUE_TEMPLATE/stable-release-discussion.md

Less re-inventing the wheel. We could add a “Known issues and workarounds” list and/or “Known issues without fixes” TODO list. Thoughts?

[github] Add stable release issue template

---

CHANGELOG.md

Added changelog for RN 0.63.1.
Only commit excluded is https://github.com/facebook/react-native/commit/ab211fa7e4c54814c2011f073134f7f274d95cda since it's just a chore for maintainers and not really related to RN itself.

generated changelog

---

scripts/changelog-generator.ts

Yargs isn't set to interpret the --verbose flag as a boolean, meaning  "--verbose true" is required to enable verbose listings instead of just "--verbose". The latter will be accepted, but will somewhat confusingly not enable verbose listings. Tell Yargs the type of the verbose flag is a boolean to support both forms.

Allow "--verbose" without to explicit boolean flag to enable verbose changelog listings

---

CHANGELOG.md
docs/publish-release.md

Adding changelog for 0.63.4 plus a super minor fix picked up by `yarn format`.

Add changelog for 0.63.4
