react-native-community/releases

README.md
I get asked about this all the time, it would be useful to have a central place to link to.
=> Explain how commits make it into a release

CHANGELOG.md
=> fix typo: babel-preset-react-native

CHANGELOG.md
Add a small section about known issues of RN 56.
=> Update Known issue section

CHANGELOG.md
Release v0.56 had incorrect link to changes. Analog to PR #28.
=> Fix format of changelog

CHANGELOG.md
Adding notes for 0.57.x versions released until now.
=> Add Release Notes for the new versions

CHANGELOG.md
as title.
Putting it here before the actual release, just to make sure it can be double-checked.
=> Changelog for 0.57.4

README.md
correcting the coma that no put on and not add on
=> correcting Coma

CHANGELOG.md
Correct spelling mistakes
Suppres -> Suppress
=> CHANGELOG -Correct spelling mistakes

CHANGELOG.md
Just a quick addin to tell everyone to update React properly ;)
=> quick placeholder for 0.57.5 changelog

CHANGELOG.md
changelog for new patch release.
=> Changelog 0.57.8

CHANGELOG.md, README.md
* fix the wordiness of the README
* tweak the release notes for all 0.58.x versions
* add the changelog for 0.58.4
=> Chore: cleanup & 0.58.4

.github/ISSUE_TEMPLATE.md
=> Chose: adding a simple issue template

CHANGELOG.md
=> Changelog for 0.58.6

CHANGELOG.md
=> Changelog 0.59.3

CHANGELOG.md
Updating the changelog with 0.59.4 relevant informations.
=> Add changelog for 0.59.4

CHANGELOG.md
=> 0.59.5 changelog

CHANGELOG.md
Add changelog entry for 0.59.9 release.
=> Add changelog entry for 0.59.9 release

CHANGELOG.md
super quick PR to add a couple lines about 0.59.10
=> 0.59.10 changelog

CHANGELOG.md
This adds a missing entry for 0.60 based on feedback from @pvinis .
=> Add entry for pvinis's change around exception handling on ios

CHANGELOG.md
we kinda lagged behind with the release notes, this aims to fix it.
=> adding patch releases for 0.60

CHANGELOG.md
=> adding patch releases for 0.60.5

README.md
This is a confusion I’ve always had and maybe other people have as well.
Possibly reduce the number of cherry-pick requests.
=> Clarify that all commits from master are released

CHANGELOG.md
=> Add 0.61.0

CHANGELOG.md
Added changelog for two latest releases
=> Add new changelog entries

changelog-generator.js
Added --verbose option  to changelog_generator.  This option outputs internal changes as well as public facing changes.  You can discover the new option through -help option.
=> add verbose option

CHANGELOG.md, package.json, scripts/__tests__/__snapshots__/changelog-generator.test.js.snap, scripts/__tests__/changelog-generator.test.js, scripts/changelog-generator.js, yarn.lock
Updated the gist with the new output https://gist.github.com/alloy/43896e2d82b6e2c99e5e85eb713b0306#file-stdout-md
=> [changelog-generator] Some detection and formatting fixes

babel.config.js, package.json, scripts/__tests__/changelog-generator.test.ts, scripts/changelog-generator.ts, tsconfig.json, yarn.lock
=> [changelog-generator] Convert to TypeScript

README.md, docs/generate-changelog.md, docs/publish-release.md, docs/release-process.md
Addresses more feedback from this PR https://github.com/react-native-community/releases/pull/165. Only one I omitted was https://github.com/react-native-community/releases/pull/165#discussion_r390454476
=> [docs] Incorporate more feedback

docs/generate-changelog.md, package.json, scripts/changelog-generator.ts
Also made a small change to not require the user to specify the location of the existing CHANGELOG file.
=> [docs] Add generate-changelog doc

scripts/changelog-generator.ts
When going through the Unknowns in the 0.62 changelog, I noticed that there were a lot of commits that have some kind of "changelog" in it but fail to match up for various reasons.
This PR moves anything that is "unknown" but has the word "changelog" in it to a new Failed section so we can dig into why they failed and hopefully add regression tests.
Here's the Failed commits for 0.62:
- Unstable_enableLogBox ([dd8e5f468a](https://github.com/facebook/react-native/commit/dd8e5f468a29e299647ffbd0887f53afd24936e3) by [@rickhanlonii](https://github.com/rickhanlonii))
- Avoid throwing exceptions when the host activity is not FragmentActivity ([7cfabf42b8](https://github.com/facebook/react-native/commit/7cfabf42b816de758d8e52896bbab0c50e3a802a))
- Add extra logging information in RN Android …
=> Add failed section

CHANGELOG.md
This is a small PR to fix an issue we noticed at upgrade-helper, basically the content that we have at the top of the diff is not linking properly to the `CHANGELOG.md` versions because they don't follow any convention, this PR fixes that.
Make sure that all the versions start with `v` and have a patch 🙂
=> Maintain consistency between version titles

CHANGELOG.md, docs/publish-release.md, scripts/changelog-generator.ts
The details are in the commits
=> [CHANGELOG] Add v0.62.1 entry

docs/publish-release.md
The url for setting up the environment has changed in the react-native website.
This points link to the new url
=> docs: change url of the environment setup

CHANGELOG.md
This is just a draft of 0.63.2 changelog. I am working on it. Contributions welcome1
=> Add changelog for 0.63.2

scripts/__tests__/changelog-generator.test.ts
I think a rename from master -> main forgot this
=> Fix getFirstCommitAfterForkingFromMain-test
